name: Sync Translation.io

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  translation_sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.1

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Pull latest master locally
        run: |
          git fetch origin
          git checkout main
          git pull origin main

      - name: Generate Unique Branch Name
        id: branch_name
        run: echo "sync-translation-io-$(date +'%s')"> branch_name.txt

      - name: Create Branch
        # run: git checkout -b $(cat branch_name.txt)
        run: git checkout -b boy-im-tired


      - name: Run translation sync
        run: |
          bundle exec rake translation:sync

      - name: Commit and push changes
        run: |
          # Author identity
          git config --global user.name "Florence-Njeri"
          git config --global user.email "flonsie17@gmail.com"
          git add .
          git commit -m "Automated translation.io sync"
          git push origin boy-im-tired

      - name: Open Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "Auto-generated Translation Sync PR"
          title: "Auto-generated Translation.io Sync PR"
          body: "This PR was automatically generated to synchronize translations."
          base: main
          labels: sync-translations
          branch: boy-im-tired
