name: Sync Translation.io

on:
  push:
    branches:
      - main
 # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  translation_sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.1

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Pull latest master locally
        run: |
          git fetch origin
          git checkout main
          git pull origin main

      - name: Generate Unique Branch Name
        id: branch_name
        run: echo "sync-translation-io-$(date +'%Y%m%d')-$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 6 | head -n 1)" > branch_name.txt

      - name: Create Branch
        run: git checkout -b $(cat branch_name.txt)

      - name: Run translation sync
        run: |
          bundle exec rake translation:sync

      - name: Commit and push changes
        run: |
         # Author identity
          set -x
          git config --global user.name "Florence-Njeri"
          git config --global user.email "flonsie17@gmail.com"
          date +%s > README.md 
          git add .
          git commit -m "Automated translation.io sync"

       - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: $(cat branch_name.txt)

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.2.4 # use 4.2.4 https://github.com/peter-evans/create-pull-request/releases/tag/v4.2.4
        with:
          commit-message: "Auto-generated Translation Sync PR"
          title: "Auto-generated Translation.io Sync PR"
          body: "This PR was automatically generated to synchronize translations."
          base: main
          head: sync-translation-io-$(date +'%s')